services:
  nginx:
    container_name: reverse-proxy
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - transcend
    env_file:
      - ./.env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - media_data:/app/media:ro  # âœ… Ensure media volume is shared with NGINX
    depends_on:
      - django
      - react
    restart: always


  react:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    networks:
      - transcend
    depends_on:
      - postgresql
      - django

  django:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: ./script.sh
    expose:
      - "8000"
    env_file:
      - ./.env
    networks:
      - transcend
    depends_on:
      - postgresql
    volumes:
      - static_data:/app/static
      - media_data:/app/media

  postgresql:
    container_name: postgresql
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    networks:
      - transcend
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:
  react_node_modules:
  media_data:
  static_data:

networks:
  transcend:
    name: transcend
    driver: bridge

